### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by skess42** [vanilla-technologies/mcfunction-debugger#1]
### In Progress
- [x] ~
- [x] better messages for failing tests (currently we only get `Added tag "failure" to test`. We could at least add zero to the incorrect score or maybe find a way to get an even fancier message into the log)
- [x] Migrate existing tests;
- [x] #19

### In Progress
- [x] ~
- [x] schedule function twice for the same tick (append), the function may only be executed once
- [x] schedule append - two schedules in two different ticks are both executed
- [x] schedule two different functions for the same tick (append), both are executed
- [x] schedule of two functions: if beakpoint, the second schedule is delayed
- [x] schedule clear
- [x] Order of multiple schedules in the same tick
- [x] schedule replace - only second schedule is executed

## Context
- [ ] execute in function changes dimension?
- [ ] restore dimension when
  - [ ] returning into entity context
  - [ ] returning into server context
  - [ ] resuming from breakpoint into entity context
  - [ ] resuming from breakpoint into server context
  
### In Progress
- [x] ~
- [x] function call without execute
- [x] execute as function visits all selected entities exacly once and changes executor
- [x] execute at function visits all selected positions exacly once and keeps entity executor
- [x] returning into entity context restores
  - [x] executor
  - [x] position
  - [x] rotation
- [x] returning into server context restores
  - [x] executor
  - [x] position
  - [x] rotation
- [x] resuming from breakpoint into server context restores
  - [x] executor
  - [x] position
  - [x] rotation
- [x] resuming from breakpoint into entity context restores
  - [x] executor
  - [x] position
  - [x] rotation
- [x] execute rotated function changes rotation
- [x] execute at function visits all selected positions exacly once and keeps server executor

### In Progress
- [x] ~
- [x] default is anchored feet
- [x] execute anchored eyes function changes anchor
- [x] execute anchored feet function changes anchor
- [x] anchored eyes propagates to nested function call
- [x] anchor eyes is restored when returning from function call with anchor feet
- [x] anchor feet is restored when returning from function call with anchor eyes
- [x] default anchor is restored when returning from function call with anchor eyes
- [x] anchor eyes is restored when resuming from breakpoint
- [x] anchor feet is restored when resuming from breakpoint

### In Progress
- [x] ~
- [x] Calling function in server context preserves AEC age
- [x] Command order in execute function call for two entities

### In Progress
- [x] ~
- [x] Breakpoint while iterating selector

**Comment by Adrodoc** [comment]
We don't test the dimension seperately, because chunk loading makes it difficult and there is no extra logic for it, since `execute at` includes the dimension.
